spring:
  datasource:
    url: jdbc:mysql://localhost:3307/wxshop?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    data-password: root
    # kebab case
    driver-class-name: com.mysql.cj.jdbc.Driver
    # python 常用的格式 叫做 snake case
    # driver_class_name
    # java 常用的格式 叫做 camel case
    # driverClassName
